\documentclass[8pt]{beamer}
%\usepackage [MeX]{polski}
\usepackage[utf8x]{inputenc}
\usetheme{Warsaw}
\usepackage{textpos}
\usepackage{tikz}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{hyperref}

\hypersetup{colorlinks=false}
%\logo{\includegraphics[height=0.8cm]{figure/cheese-icon.png}\vspace{220pt}}
\title {AmpliQueso Report}
\author[M.Okoniewski, A.Szabelska, M.Wiewiórka]{\includegraphics[height=1cm,width=1cm]{figure/cheese-icon.png}\\Michał Okoniewski, Alicja Szabelska, Marek Wiewiórka}
%\author { Michal Okoniewski, Alicja Szabelka, Marek Wiewiorka}

\begin{document}
<<setup, include=FALSE>>=
# smaller font size for chunks
#opts_chunk$set(size = 'footnotesize')
opts_chunk$set(results='asis', echo=gvVerbose)

@
\begin{frame}
\titlepage
\end{frame}

%hackinf for logo
\addtobeamertemplate{frametitle}{}{%
\begin{tikzpicture}[remember picture,overlay]
\node[anchor=north east,yshift=2pt] at (current page.north east) {\includegraphics[height=0.8cm]{figure/cheese-icon.png}};
\end{tikzpicture}}


\begin{frame}
\frametitle{AmpliQueso TOC}
\tableofcontents
\end{frame}

\section{Report parameters}
\begin{frame}[fragile]{Report parameters}
\fontsize{7pt}{7.2}\selectfont
\begin{center}
<<reportParTable>>=
kable(reportParams, longtable=FALSE, booktabs=TRUE)
@
\end{center}
\end{frame}

\section {RNA--seq count analysis}
\subsection{Differentially expressed genes}
\begin{frame}[fragile]{Differentially expressed genes}
\fontsize{7pt}{7.2}\selectfont
\begin{center}
<<countTable>>=
#xtable(t, caption ="Counts table", label ="CT",tabular.environment='longtable',floating=FALSE)
library(knitr)
kable(countRepTable, longtable=TRUE, booktabs=TRUE)
@
\end{center}
\end{frame}


\subsection {Volcano plot}
\begin{frame}[fragile]{Volcano plot}
%\fontsize{6pt}{7.2}\selectfont
\begin{center}
<<volcanoPlot, fig.width=10, fig.height=10, out.width='.55\\linewidth'>>=
#comment, no comment
plot(foldChange, -log(countTableTran[,"p.value"]))
@
\end{center}
\end{frame}

\subsection {Heatmap plot}
\begin{frame}[fragile]{Heatmap plot}
\fontsize{5pt}{7.2}\selectfont
\begin{center}
<<heatmapPlot, fig.width=10, fig.height=10, out.width='.50\\linewidth'>>=
#comment, no comment
heatmap.2(countTable[rownames(countTableTranSort[1:gvTopN,]),],trace="none")

@
\end{center}
\end{frame}


\subsection {Distributions of counts}
\begin{frame}[fragile]{Distributions of counts}
\fontsize{5pt}{7.2}\selectfont
\begin{center}
<<distrPlot, fig.width=10, fig.height=10, out.width='.55\\linewidth'>>=
legendPaths<-strsplit( colnames(countTable),"/")
    legendSampl<-rep("",ncol(countTable))
    y<-rep(0,binsNum)
for(s in 1:ncol(countTable)){   
        #remove outliers by taking 1st and 99th percentile of counts
        countTable[,s] <- log2(countTable[,s]+0.01)
        countPercentiles<-quantile(countTable[,s],probs=c(0.01,0.99,0.9))
        #50+1 for seq function due to its formula: by = ((to - from)/(length.out - 1)
        bins <-seq(countPercentiles[1],countPercentiles[2],length.out=binsNum+1)
        for(b in 2:length(bins)){         
            y[b]<-length(countTable[,s][countTable[,s]>=bins[b-1] & countTable[,s]<bins[b]])   
        }
        if(s == 1){
          plot(bins,y,type="l", col=(rainbow(s)[s]),ylim<-c(0,countPercentiles[2]),ylab="counts")
        }
        else{
          lines(bins,y, col=(rainbow(s)[s])   )     
        }
        points(bins,y,col=(rainbow(s)[s]), cex=0.5, pch=1)
        #get filenames from fullpaths
        legendSampl[s]<-unlist(legendPaths[s])[length(unlist(legendPaths[s]))]
    }
    yPercentile<-quantile(y,probs=c(0.99))
      legend(legend=legendSampl,x=countPercentiles[3],y=yPercentile[1],lty=c(1,1),col=rainbow(ncol(countTable)) )

@
\end{center}
\end{frame}
\section{Camels' analysis}
\subsection{Camels' measures}
\begin{frame}[fragile,allowframebreaks]{Camels' measures}
\fontsize{5pt}{7.2}\selectfont
<<camelsTable>>=
#xtable(t, caption ="Counts table", label ="CT",tabular.environment='longtable',floating=FALSE)
kable(camelsRankTableSort, longtable=TRUE, booktabs=TRUE)
@
\end{frame}
%\subsection{Camels' plots}
%\begin{frame}[fragile,allowframebreaks]{Camels' plots}
%\fontsize{5pt}{7.2}\selectfont
%TBD
%<<camelsPlots>>=
%#xtable(t, caption ="Counts table", label ="CT",tabular.environment='longtable',floating=FALSE)
%@
%\end{frame}
\section {SNPs calling}
\begin{frame}[fragile,allowframebreaks]{SNPs calling}
\fontsize{5pt}{7.2}\selectfont
SNPs set difference (iT1 minus iT2)
<<SNPsTable1>>=
if(!is.null(gvRefSeqFile) && nrow(snpDiffSickCountFilter) > 0){
  
  kable(snpDiffSickCountFilter, longtable=TRUE, booktabs=TRUE,row.names=FALSE)
}
#else{
#  print("SNPs set difference iT1 minus iT2 is empty.")
#}
@
SNPs set difference (iT2 minus iT1)
<<SNPsTable2>>=
if(!is.null(gvRefSeqFile) && nrow(snpDiffHealthyCountFilter) > 0){
  kable(snpDiffHealthyCountFilter, longtable=TRUE, booktabs=TRUE,row.names=FALSE)
}
#else{
#  print("SNPs set difference iT2 minus iT1 is empty.")
#}
@
\end{frame}

\end{document}